version: '3.7'
services:
  bitbattle_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  bitbattle_node:
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - bitbattle_db
